RentCar/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RentCar.DAL;
using RentCar.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RentCar.Controllers
{
    public class AboutController : Controller
    {
        private readonly AppDbContext _dbContext;

        public AboutController(AppDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        public async Task<IActionResult> Index()
        {
            return View(new AboutIndexViewModel { 
                AboutSection = await _dbContext.AboutSections.FirstOrDefaultAsync()
            });
        }
    }
}

RentCar/Controllers/PartnerController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RentCar.DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RentCar.Controllers
{
    public class PartnerController : Controller
    {
        private readonly AppDbContext _dbContext;

        public PartnerController(AppDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _dbContext.PartnerInfoCards.ToListAsync());
        }
    }
}

RentCar/Views/Shared/Components/Header/Default.cshtml
@model Logo

<!--==================== HEADER START ====================-->
<header class="header">
    <div class="navbar__container">
        <nav>
            <div class="logo">
                <img src="~/image/@Model.Image" alt="Logo Image">
            </div>
            <div class="hamburger">
                <div class="line1"></div>
                <div class="line2"></div>
                <div class="line3"></div>
            </div>
            <ul class="nav__links">
                <li><a asp-action="Index" asp-controller="Home">Ana səhifə</a></li>
                <li><a asp-action="Index" asp-controller="About">Haqqımızda</a></li>
                <li><a asp-action="Index" asp-controller="Partner">Tərəfdaşlarımız</a></li>
                <li><a asp-action="Index" asp-controller="Car">Avtomobillər</a></li>
                <li><a asp-action="Index" asp-controller="Contact">Əlaqə</a></li>

                <!--=== darkmode ===-->
                <input type="checkbox" class="checkbox" id="checkbox">
                <label for="checkbox" class="label">
                    <i class="fas fa-moon"></i>
                    <i class="fas fa-sun"></i>
                    <div class="ball"></div>
                </label>
                <!--=== end ===-->
                @if (User.Identity.IsAuthenticated)
                {
                    @*<li style="margin-left: 1rem; font-size: 12px; text-decoration: underline; text-underline-offset: 2px; font-style:italic;">@User.Identity.Name</li>*@
                    <li><a class="login__button" asp-action="Logout" asp-controller="Account">Çıxış</a></li>
                }
                else
                {
                    <li><a class="login__button" asp-action="Login" asp-controller="Account">Giriş</a></li>
                }
            </ul>
        </nav>
    </div>
</header>
<!--==================== HEADER END ====================-->